---
title: "masterThesis"
output: html_document
date: '2022-11-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidyquant)
library(quantmod)
library(corrplot)
library(corrr)
```


```{r}
stock_list <- tibble(selector = c("SPY", "XLC", "XLY", "XLP", "XLE", "XLF", "XLV", "XLI", "XLB", "XLRE", "XLK", "XLU"))

daily_returns <- stock_list %>%
  tq_get(get = "stock.prices", from = "2000-01-01", to = "2022-01-01")

quarterly_returns <- daily_returns %>% 
  group_by(selector) %>%
  tq_transmute(select     = adjusted, 
               mutate_fun = periodReturn, 
               period     = "quarterly", 
               col_rename = "quarterly.returns") %>% 
   mutate(qtr = quarter(date))

unpivot <- quarterly_returns %>% 
  pivot_wider(names_from = selector, values_from = quarterly.returns) %>% 
  select(-date)

```

# Quartrer 1
```{r}
unpivot %>% 
  filter(qtr == 1) %>% 
  select(-qtr) %>% 
  cor() %>% 
  corrplot(method = 'number')
```

# Quartrer 2
```{r}
unpivot %>% 
  filter(qtr == 2) %>% 
  select(-qtr) %>% 
  cor() %>% 
  corrplot(method = 'number')
```

# Quartrer 3
```{r}
unpivot %>% 
  filter(qtr == 3) %>% 
  select(-qtr) %>% 
  cor() %>% 
  corrplot(method = 'number')
```

# Quartrer 4
```{r}
unpivot %>% 
  filter(qtr == 4) %>% 
  select(-qtr) %>% 
  cor() %>% 
  corrplot(method = 'number')
```

# Quartrer 1
```{r}
unpivot %>% 
  filter(qtr == 1) %>% 
  select(-qtr) %>% 
  correlate() %>% 
  rearrange() %>% 
  shave() %>% 
  rplot(print_cor = TRUE)
```


# Quartrer 2
```{r}
unpivot %>% 
  filter(qtr == 1) %>% 
  select(-qtr) %>% 
  correlate() %>% 
  rearrange() %>% 
  shave() %>% 
  rplot(print_cor = TRUE)
```


# Quartrer 3
```{r}
unpivot %>% 
  filter(qtr == 1) %>% 
  select(-qtr) %>% 
  correlate() %>% 
  rearrange() %>% 
  shave() %>% 
  rplot(print_cor = TRUE)
```


# Quartrer 4
```{r}
unpivot %>% 
  filter(qtr == 1) %>% 
  select(-qtr) %>% 
  correlate() %>% 
  rearrange() %>% 
  shave() %>% 
  rplot(print_cor = TRUE)
```
#SPY
```{r}
qt1 <- unpivot %>% 
  filter(qtr == 1) %>% 
  select(-qtr) %>% 
  correlate() %>% 
  filter(term == "SPY")

qt2 <- unpivot %>% 
  filter(qtr == 2) %>% 
  select(-qtr) %>% 
  correlate() %>% 
  filter(term == "SPY")

qt3 <- unpivot %>% 
  filter(qtr == 3) %>% 
  select(-qtr) %>% 
  correlate() %>% 
  filter(term == "SPY")

qt4 <- unpivot %>% 
  filter(qtr == 4) %>% 
  select(-qtr) %>% 
  correlate() %>% 
  filter(term == "SPY")

binded <- bind_rows(qt1, qt2, qt3, qt4)

binded %>% 
  select(-term, -SPY) %>% 
  mutate(qtr = c(1,2,3,4)) %>% 
  pivot_longer(!qtr, names_to = "sector", values_to = "correlation") %>% 
  ggplot(aes(qtr, correlation)) +
  geom_line(aes(colour = sector))

```


```{r}
quarterly_returns %>%
    ggplot(aes(x = year(date), y = quarterly.returns, fill = selector)) +
    geom_bar(position = "dodge", stat = "identity") +
    labs(title = "FANG: Annual Returns", 
         subtitle = "Mutating at scale is quick and easy!",
         y = "Returns", x = "", color = "") +
    scale_y_continuous(labels = scales::percent) +
    coord_flip() +
    theme_tq() +
    scale_fill_tq()
```


