#with log
```{r}
library(Quandl)
library(PerformanceAnalytics)
library(ggplot2)
library(forecast)
library(tidyverse)
library("timetk")
library("tidyquant")
```

```{r}
Quandl.api_key("4nDDuxoarbX1eR9z7KY-")
EDate <- as.Date(Sys.Date())-365*3
SDate <- as.Date(EDate-365*60)
YoY <- as.Date(EDate-365)

EDate
EFDate <- as.Date(Sys.Date())
SFDate <- EFDate - 365*80 
SFDate
EFDate
```

```{r}
realpersonalincomelesstransfers <- tq_get("W875RX1",
                                          from = SDate,
                                          get = "economic.data")%>% 
  tq_transmute(select = price,
               mutate_fun = periodReturn,
               period = "monthly",
               col_rename = "Value")

realpersonalincomelesstransfers %>% 
  ggplot(aes(date, Value)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "% change") +
  ggtitle('Real Personal Income Less Transfers')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```
```{r}
nonfarmpayrollemployment <- tq_get("PAYEMS",
                                          from = SDate,
                                          get = "economic.data")%>% 
  tq_transmute(select = price,
               mutate_fun = periodReturn,
               period = "monthly",
               col_rename = "Value")

nonfarmpayrollemployment %>% 
  ggplot(aes(date, Value)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Non-Farm Payroll')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```

```{r}
realpersonalconsumptionexpenditures <- tq_get("DPCERA3M086SBEA",
                                          from = SDate,
                                          get = "economic.data")%>% 
  tq_transmute(select = price,
               mutate_fun = periodReturn,
               period = "monthly",
               col_rename = "Value")

realpersonalconsumptionexpenditures %>% 
  ggplot(aes(date, Value)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Real personal Consumption Expenditure')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```
```{r}
ProducerPriceIndex <- tq_get("PPIACO",
                                          from = SDate,
                                          get = "economic.data")%>% 
  tq_transmute(select = price,
               mutate_fun = periodReturn,
               period = "monthly",
               col_rename = "Value")

ProducerPriceIndex %>% 
  ggplot(aes(date, Value)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Producer Price Index')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```
```{r}
IPI  <- tq_get("INDPRO",
                                          from = SDate,
                                          get = "economic.data")%>% 
  tq_transmute(select = price,
               mutate_fun = periodReturn,
               period = "monthly",
               col_rename = "Value")

IPI %>% 
  ggplot(aes(date, Value)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Industrial Production Index')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```
```{r}
employmentrate <- tq_get("EMRATIO",
                                          from = SDate,
                                          get = "economic.data")%>% 
  tq_transmute(select = price,
               mutate_fun = periodReturn,
               period = "monthly",
               col_rename = "Value")

employmentrate$Value <- employmentrate$Value/100
employmentrate %>% 
  ggplot(aes(date, Value)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Employment Rate')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```
```{r}
pca_data_leading <- realpersonalincomelesstransfers %>% 
  left_join(nonfarmpayrollemployment, by = "date") %>% 
  left_join(realpersonalconsumptionexpenditures, by = "date") %>%
  left_join(ProducerPriceIndex, by = "date") %>%
  left_join(IPI, by = "date") %>%
  left_join(employmentrate, by = "date") %>%
  select(-date) %>% 
  na.omit()
pca_data_leading_standardized <- scale(pca_data_leading)
pca_result_leading <- princomp(pca_data_leading)
pca_result_leading$scores
pca_result_leading$sdev
pca_summary_leading  <- summary(pca_result_leading)
pca_variances_leading  <- var(pca_result_leading$scores)
pca_cumulative_variances_leading  <- cumsum(pca_variances_leading)
pca_var_leading  <- pca_result_leading$sdev^2 / sum(pca_result_leading$sdev^2)
barplot(pca_var_leading, xlab="Principal Component", ylab="Proportion of Variance Explained")
screeplot(pca_result_leading, type="line", main="Scree Plot")
plot(pca_result_leading$scores[,1:2], col=1:nrow(pca_result_leading$scores), xlab="PC1", ylab="PC2")
pca_scores_leading <- as.data.frame(pca_result_leading$scores) %>% 
  select(Comp.1)
values_leading <- realpersonalincomelesstransfers %>% 
  left_join(nonfarmpayrollemployment, by = "date") %>% 
  left_join(realpersonalconsumptionexpenditures, by = "date") %>%
  left_join(ProducerPriceIndex, by = "date") %>%
  left_join(IPI, by = "date") %>%
  left_join(employmentrate, by = "date") %>%
  na.omit()
values_leading$index <- pca_scores_leading[,1]
plot(values_leading$date, values_leading$index)
values_leading %>% 
  ggplot(aes(date, index)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "Leading index") +
  ggtitle('Leading index for business cycle') +
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
#+annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple')


#########################################################################################################################################################
```



# Without log

```{r}
library(Quandl)
library(PerformanceAnalytics)
library(ggplot2)
library(forecast)
library(tidyverse)
library("timetk")
library("tidyquant")
```

```{r}
Quandl.api_key("4nDDuxoarbX1eR9z7KY-")
EDate <- as.Date(Sys.Date())-365*3
SDate <- as.Date(EDate-365*60)
YoY <- as.Date(EDate-365)

EDate
EFDate <- as.Date(Sys.Date())
SFDate <- EFDate - 365*80 
SFDate
EFDate
```

```{r}
realpersonalincomelesstransfers <- tq_get("W875RX1",
                                          from = SDate,
                                          get = "economic.data") %>% 
  tq_transmute(select = price, mutate_fun = to.monthly, indexAt = "firstof", col_rename = "RealPersInc")

realpersonalincomelesstransfers %>% 
  ggplot(aes(date, RealPersInc)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Real Personal Income Less Transfers')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```
```{r}
nonfarmpayrollemployment <- tq_get("PAYEMS",
                                          from = SDate,
                                          get = "economic.data") %>% 
  tq_transmute(select = price, mutate_fun = to.monthly, indexAt = "firstof", col_rename = "NonFarmPayroll") 
  
nonfarmpayrollemployment %>% 
  ggplot(aes(date, NonFarmPayroll)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Non-Farm Payroll')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```

```{r}
realpersonalconsumptionexpenditures <- tq_get("DPCERA3M086SBEA",
                                          from = SDate,
                                          get = "economic.data") %>% 
  tq_transmute(select = price, mutate_fun = to.monthly, indexAt = "firstof", col_rename = "RealPCE") 

realpersonalconsumptionexpenditures %>% 
  ggplot(aes(date, RealPCE)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Real personal Consumption Expenditure')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```

```{r}
ProducerPriceIndex <- tq_get("PPIACO",
                                          from = SDate,
                                          get = "economic.data") %>% 
  tq_transmute(select = price, mutate_fun = to.monthly, indexAt = "firstof", col_rename = "PPI") 
  
ProducerPriceIndex %>% 
  ggplot(aes(date, PPI)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Producer Price Index')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```

```{r}
IPI  <- tq_get("INDPRO",
                                          from = SDate,
                                          get = "economic.data") %>% 
  tq_transmute(select = price, mutate_fun = to.monthly, indexAt = "firstof", col_rename = "IPI") 
  

IPI %>% 
  ggplot(aes(date, IPI)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Industrial Production Index')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```
```{r}
employmentrate <- tq_get("EMRATIO",
                                          from = SDate,
                                          get = "economic.data") %>% 
  tq_transmute(select = price, mutate_fun = to.monthly, indexAt = "firstof", col_rename = "EmployRate") 

employmentrate %>% 
  ggplot(aes(date, EmployRate)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "N° of building permits") +
  ggtitle('Employment Rate')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -0.05, ymax = 0.05, alpha = .2, fill = 'purple')
```


```{r}
# S&P500 PE Ratios
SP500_PE <- tq_get("MULTPL/SP500_PE_RATIO_MONTH",
                                          from = SDate,
                                          get = "quandl")%>% 
  tq_transmute(select = value, mutate_fun = to.monthly, indexAt = "firstof", col_rename = "SP500PE") 

SP500_PE %>% 
  ggplot(aes(date, SP500PE)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "PE Ratio") +
  ggtitle('S&P 500 PE ratio')+
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = 20, ymax = 100, alpha = .2, fill = 'purple')
```


```{r}
pca_data_leading <- realpersonalincomelesstransfers %>% 
  left_join(nonfarmpayrollemployment, by = "date") %>% 
  left_join(realpersonalconsumptionexpenditures, by = "date") %>%
  left_join(ProducerPriceIndex, by = "date") %>%
  left_join(IPI, by = "date") %>%
  left_join(employmentrate, by = "date") %>% 
  select(-date) %>% 
  na.omit()

pca_data_leading_standardized <- scale(pca_data_leading)
pca_result_leading <- princomp(pca_data_leading_standardized)
pca_result_leading$scores
pca_result_leading$sdev

correlations <- cor(pca_data_leading_standardized)
print(correlations)

pca_summary_leading  <- summary(pca_result_leading)
pca_variances_leading  <- var(pca_result_leading$scores)
pca_cumulative_variances_leading  <- cumsum(pca_variances_leading)

pca_var_leading  <- pca_result_leading$sdev^2 / sum(pca_result_leading$sdev^2)
barplot(pca_var_leading, xlab="Principal Component", ylab="Proportion of Variance Explained")
screeplot(pca_result_leading, type="line", main="Scree Plot")

plot(pca_result_leading$scores[,1:2], col=1:nrow(pca_result_leading$scores), xlab="PC1", ylab="PC2")

pca_scores_leading <- as.data.frame(pca_result_leading$scores) %>% 
  select(Comp.1)

values_leading <- realpersonalincomelesstransfers %>% 
  left_join(nonfarmpayrollemployment, by = "date") %>% 
  left_join(realpersonalconsumptionexpenditures, by = "date") %>%
  left_join(ProducerPriceIndex, by = "date") %>%
  left_join(IPI, by = "date") %>%
  left_join(employmentrate, by = "date") %>%
  na.omit()

values_leading$index <- pca_scores_leading[,1]
plot(values_leading$date, values_leading$index)

values_leading %>% 
  ggplot(aes(date, index)) + 
  geom_line() +
  scale_x_date(name = "Year", date_minor_breaks = "10 year") + 
  scale_y_continuous(name = "Leading index") +
  ggtitle('Leading index for business cycle') +
  annotate("rect", xmin = as.Date("2020/02/01"), xmax = as.Date("2020/04/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2007/12/01"), xmax = as.Date("2009/06/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("2001/03/01"), xmax = as.Date("2001/11/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple') +
  annotate("rect", xmin = as.Date("1990/07/01"), xmax = as.Date("1991/03/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1981/07/01"), xmax = as.Date("1982/11/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1980/01/01"), xmax = as.Date("1980/07/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple')+
annotate("rect", xmin = as.Date("1973/11/01"), xmax = as.Date("1975/05/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1969/12/01"), xmax = as.Date("1970/11/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple')+
  annotate("rect", xmin = as.Date("1960/04/01"), xmax = as.Date("1961/02/01"), ymin = -3.5, ymax = 5, alpha = .2, fill = 'purple')

```