---
title: "Stocks"
output: html_document
date: "2023-01-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyquant)
library(PerformanceAnalytics)
library(tidyr)
library(dplyr)
library(psych)
library(ggplot2)
```

# Communication
```{r}
# Get communication sector data

communication_stocks <- tq_get(c("GOOGL","T", "META", "GOOG", "LUMN", "VZ", "WBD", "CMCSA", "DIS", "NFLX", "PARA", "TMUS", "DISH", "ATVI", "MTCH", "FOXA", "IPG", "NWSA", "LYV", "EA", "TTWO", "OMC", "NWS", "FOX", "CHTR"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

communication_stocks_returns <- communication_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

communication_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for communication stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = "none") +
  theme_classic()

communication_stocks_returns %>%
  group_by(symbol) %>%
  summarise(mean = mean(returns),
            sd = sd(returns)) 
```
# Consumer discretionary
```{r}
# Get consumer discretionary sector data

cons_discr_stocks <- tq_get(c("TSLA", "F", "AMZN", "CCL", "GM", "NCLH", "SBUX", "VFC", "TGT", "NKE", "LVS", "TJX", "RCL", "ETSY", "LOW", "EBAY","KMX", "HD", "EXPE", "MGM", "NWL", "DHI", "LKQ", "ROST", "BBWI"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

cons_discr_stocks_returns <- cons_discr_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

cons_discr_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for consumer discretionary stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()
```

# Consumer staples
```{r}
cons_staples_stocks <- tq_get(c("KO", "MO", "KHC", "KDP", "PG", "PEP", "MDLZ", "WMT", "WBA","CL","GIS","KR", "CAG", "PM", "STZ", "ADM"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

cons_staples_returns <- cons_staples_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

cons_staples_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for consumer staples stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()
```

# Energy
```{r}
energy_stocks <- tq_get(c("XOM", "KMI", "SLB", "OXY", "MRO", "CTRA", "HAL", "CVX", "EQT", "DVN", "WMB", "BKR", "COP", "APA", "MPC"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

energy_stocks_returns <- energy_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

energy_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for energy stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()
```

# Financial
```{r}

financial_stocks <- tq_get(c("BAC", "WFC", "C", "JPM", "HBAN", "BK", "KEY", "RF","SCHW", "MS", "TFC", "USB", "IVZ", "FITB", "SYF", "PNC", "STT", "CFG", "BEN", "GS", "COF", "FRC", "NDAQ"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

financial_stocks_returns <- financial_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

financial_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for financial stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()


```

# Industrial
```{r}

industrial_stocks <- tq_get(c("AAL","DAL", "UAL", "GE", "CSX", "BA", "LUV", "RTX", "CAT", "CARR", "WM", "NOC", "ALK", "JCI", "RSG", "FAST", "EMR", "LMT", "UPS", "HON", "SWK", "LHX", "PCAR", "UNP", "MMM", "ETN", "PNR", "HWM", "GD", "MAS", "FDX", "OTIS", "IR", "GNRC", "CPRT", "TXT", "FTV"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

industrial_stocks_returns <- industrial_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

industrial_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for industrial stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()

```

# Healthcare
```{r}
healthcare_stocks <- tq_get(c("PFE", "VTRS", "CVS", "BMY", "BAX", "JNJ", "BSX", "MDT", "ABBV", "MRK", "UNH", "ABT", "GILD", "MRNA", "CNC", "CAH", "OGN", "ZTS", "DXCM", "TECH", "TMO", "EW", "CTLT", "XRAT", "DHR", "ISRG", "AMGN", "LLY", "ZBH", "CI", "VRTX"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

healthcare_stocks_returns <- healthcare_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

healthcare_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for healthcare stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()


```

# Technology
```{r}

technology_stocks <- tq_get(c("AAPL", "AMD", "NVDA", "INT", "MSFT", "CSCO", "MU", "HPE", "PYPL","CRM", "QCOM", "HPQ", "FIS", "FTNT", "AMAT", "CTSH", "ORCL", "V", "MA", "WDC", "MCHP", "ENPH", "FISV", "TXN", "GLW", "ON", "ADBE", "IBM", "JNPR", "ACN", "GEN", "APH", "NXPI", "ANET", "AVGO", "FSLR", "ADI"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

technology_stocks_returns <- technology_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

technology_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for technology stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()

```

# Materials
```{r}
materials_stocks <- tq_get(c("FCX", "NEM", "AMCR", "MOS", "DOW", "IP", "DD", "CF", "CTVA", "LIN", "BALL", "NUE", "LYB", "STLD", "ALB", "IFF"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

materials_stocks_returns <- materials_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

materials_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for materials stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()
```

# Real Estate
```{r}

real_estate_stocks <- tq_get(c("VICI", "HST", "KIM", "WY", "INVH", "VNO", "PEAK", "PLD", "VTR", "O", "EQR", "AMT", "SPG", "CCI", "CBRE", "WELL", "UDR", "IRM", "DLR", "BXP"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

real_estate_stocks_returns <- real_estate_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

real_estate_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for real estate stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()
```

# Utilities
```{r}
utilities_stocks <- tq_get(c("PCG", "EXC", "AES", "NEE","CNP", "FE", "PPL", "NRG", "AEP","SO", "D", "NI", "DUK", "AEE", "XEL", "PEG", "ES", "ETR", "EIX", "CEG", "CMS", "ED", "SRE", "WEC", "EVRG"),
                      from = "2020-01-01",
                      get = "stock.prices") %>% 
                      rename(Date = date)

utilities_stocks_returns <- utilities_stocks %>%
  group_by(symbol) %>%                            
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'returns',
               type = "log")

utilities_stocks_returns %>%
  ggplot(aes(x = Date, y = returns)) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~symbol, scales = "free_y") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Daily returns for utilities stock") +
  labs(x = "Date", y = "Returns") +
  scale_color_brewer(palette = "Set2",
                     name = "",
                     guide = FALSE) +
  theme_classic()
```

# Combination of dataframes and summary statistics
```{r}

# Create a list of the data frames
df_list <- list(communication_stocks, cons_discr_stocks, cons_staples_stocks, energy_stocks, financial_stocks, healthcare_stocks, industrial_stocks, materials_stocks, real_estate_stocks, technology_stocks, utilities_stocks)

# Combine the data frames by rows
stocks_df <- reduce(df_list, bind_rows)

df_list_returns <- list(communication_stocks_returns, cons_discr_stocks_returns, cons_staples_returns, energy_stocks_returns, financial_stocks_returns, healthcare_stocks_returns, industrial_stocks_returns, materials_stocks_returns, real_estate_stocks_returns, technology_stocks_returns, utilities_stocks_returns)

returns_df <- reduce(df_list_returns, bind_rows)

# Creation of dataframe
summary_returns <- returns_df %>%
  group_by(symbol) %>%
  summarise(mean = mean(returns),
            sd = sd(returns)) 

summary_returns$annualmean <- (1+summary_returns$mean)^(251)-1

summary_returns$annualsd <- summary_returns$sd * sqrt(252)

summary_returns$sharpe <- (summary_returns$annualmean - 0.05)/summary_returns$annualsd

summary(summary_returns)

# Plotting sharpe ratios for each sector
ggplot(data = summary_returns, aes(x = reorder(symbol, -sharpe), y = sharpe)) +
  geom_bar(stat = "identity") +
  xlab("Company Name") +
  ylab("Sharpe Ratio") +
  ggtitle("Companies with the highest Sharpe Ratio") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

companies_sorted <- summary_returns %>%
  arrange(desc(sharpe))
  
```

# Creation of eigenportfolios
```{r}

# Getting data ready
returns_df_ts <- scale(returns_df %>% 
  spread(key = symbol, value = returns) %>% 
  select(-Date) %>% 
  na.omit())

# PCA on stocks
eigenportfolios <- prcomp(returns_df_ts, scale= TRUE)

#Creation of eigenvectors
eigenvectors <- eigenportfolios$rotation

# Calculation and assigning weights
weights <- as.data.frame(eigenvectors[,1] / sum(eigenvectors[,1]))
weights <- add_rownames(weights, var = "rowname")

colnames(weights)[1] <- "symbol"
colnames(weights)[2] <- "weight"

# Merged data and creation of portfolio return
merged_data <- merge(returns_df, weights, by = "symbol")
merged_data$portfolio <- merged_data$weight * merged_data$returns

# Creation of eigenportfolio
eigenportfolio1 <- merged_data %>% 
  pivot_wider(names_from = symbol, values_from = portfolio) %>% 
  select(-weight, -returns) %>% 
  group_by(Date) %>%
  summarize_all(sum, na.rm = TRUE)

eigenportfolio1$return <- rowSums(eigenportfolio1[,-1], na.rm = TRUE)

# Plotting historical portfolio returns
eigenportfolio1 %>% 
  ggplot(aes(x = Date, y = return)) +
           geom_line()

# Plotting cumulative portfolio returns
eigenportfolio1$cumulative <- cumprod(eigenportfolio1$return+1)-1

eigenportfolio1 %>% 
  ggplot(aes(x = Date, y = cumulative)) +
           geom_line()




```

## CODE WHERE YOU CAN TEST AND SEE HOW IT WORKS, SUBSTITUTE 10 TO n IN THE INITIAL for LOOP
```{r}

# List with saved plots
plots_list <- list()

# Data frame where to save results
results <- data.frame()
n <- ncol(eigenvectors)

for (i in 1:n) {
  # Calculation and assigning weights
  weights <- as.data.frame(eigenvectors[,i] / sum(eigenvectors[,i]))
  weights <- add_rownames(weights, var = "rowname")

  colnames(weights)[1] <- "symbol"
  colnames(weights)[2] <- "weight"

  # Merged data and creation of portfolio return
  merged_data <- merge(returns_df, weights, by = "symbol")
  merged_data$portfolio <- merged_data$weight * merged_data$returns

  # Creation of eigenportfolio
  eigenportfolio <- merged_data %>% 
    pivot_wider(names_from = symbol, values_from = portfolio) %>% 
    select(-weight, -returns) %>% 
    group_by(Date) %>%
    summarize_all(sum, na.rm = TRUE)

  eigenportfolio$return <- rowSums(eigenportfolio[,-1], na.rm = TRUE)
  
  cat(paste("Processing column:", colnames(eigenvectors)[i]), "\n")
  
  # Add the iteration number column to the eigenportfolio dataframe
  eigenportfolio$iteration <- i

  # Append the results of the current iteration to the results dataframe
  results <- rbind(results, eigenportfolio)

  # Plotting historical portfolio returns
  eigenportfolio %>% 
    ggplot(aes(x = Date, y = return)) +
    geom_line()
  
  # Plotting cumulative portfolio returns
  eigenportfolio$cumulative <- cumprod(eigenportfolio$return+1)-1

  cum_plot <- eigenportfolio %>% 
    ggplot(aes(x = Date, y = cumulative)) +
    geom_line()
  
   # Append the historical plot to the list
    plots_list[[paste0("iteration_", i, "_historical")]] <- cum_plot
}

# Dataframe with all the created portfolios
all_portfolios <- results %>% 
  select(Date, return, iteration) %>% 
  spread(iteration, return)

# Statistical summary of each portfolio
summary(all_portfolios)

# Print all of the created plots
print(plots_list)

```


# IDK IF WORKS
```{r}
library(psych)


returns_df_ts <- returns_df %>% 
  spread(key = symbol, value = returns)

pca_data <- returns_df_ts %>% 
  select(-Date) %>% 
  na.omit()

pca_sectors <- prcomp(pca_data)
pca_sectors$scores
pca_sectors$sdev

# Calculate correlation matrix
cor_matrix <- cor(pca_data)

# Calculate eigenvectors and eigenvalues
eigen_results <- eigen(cor_matrix)
eigenvectors <- eigen_results$vectors

# Create eigenportfolio
eigenportfolio <- eigenvectors[,1]


# Checking shape of data
bartlett.test(returns_df_ts)

# Calculate the Kaiser-Meyer-Olkin (KMO) measure for the dataset
KMO(returns_df_ts)

pca_summary  <- summary(pca_sectors)
pca_variances  <- var(pca_summary$scores)
pca_cumulative_variances  <- cumsum(pca_variances)

pca_var  <- pca_sectors$sdev^2 / sum(pca_sectors$sdev^2)
barplot(pca_var, xlab="Principal Component", ylab="Proportion of Variance Explained")
screeplot(pca_sectors, type="line", main="Scree Plot")

plot(pca_sectors$scores[,1:2], col=1:nrow(pca_sectors$scores), xlab="PC1", ylab="PC2")

pca_scores <- as.data.frame(pca_sectors$scores) %>% 
  select(Comp.1)


```


